### ISSUE TITLE
Problem is resolved even though the actual issue is not resolved

### ISSUE THREAD

**Issue by kanchalwar** [mediro-ict/activegate_python_ssl_plugin#1]
It is observed that even though the issue is actually not resolved, the Problem on the Dynatrace console is Resolved in approximately 40 mins. Please advise.

**Comment by leonvzGit** [comment]
this is by design , Denyatrace closes the problem automatically, it is related to https://answers.dynatrace.com/spaces/482/dynatrace-open-qa/questions/225692/does-dynatrace-close-automatically-problem-after-a.html
A new problem will be opened if the certificate is not updated, it is proportional to the polling period chosen

**Comment by leonvzGit** [comment]
Closed due to no reply

**Comment by kanchalwar** [comment]
Thanks Leon. That helps for now. Will get in touch in case of any further
information needed.

Best regards & thanks
Sandeep Kanchalwar
